name: Test FibBot Action

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: rust-lang/setup-rust@v1
        with:
          rust-version: stable

      - name: Build and run FibBot
        run: |
          cargo build --release
          ./target/release/fibbot
